// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

const FirebaseOptions firebaseOptions = FirebaseOptions(
  apiKey: 'YOUR_API_KEY',
  appId: 'YOUR_APP_ID',
  messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
  projectId: 'YOUR_PROJECT_ID',
  authDomain: 'YOUR_AUTH_DOMAIN',
  storageBucket: 'YOUR_STORAGE_BUCKET',
  measurementId: kIsWeb ? 'YOUR_MEASUREMENT_ID' : null,
);

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBthGXW1FU2bJ3L7yPMKw0jU7ns37Th2q8',
    appId: '1:536108233592:web:1d5ca77b1cc815ae30ce8d',
    messagingSenderId: '536108233592',
    projectId: 'talk-easy-7b3a7',
    authDomain: 'talk-easy-7b3a7.firebaseapp.com',
    storageBucket: 'talk-easy-7b3a7.firebasestorage.app',
    measurementId: 'G-GYZXE1N79G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU7KLeYE0rShXGwPv5Y8XZe1hQBrEkItg',
    appId: '1:536108233592:android:c0b736a6f6e9a44b30ce8d',
    messagingSenderId: '536108233592',
    projectId: 'talk-easy-7b3a7',
    storageBucket: 'talk-easy-7b3a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2ilJGagVaZM5bYPxwt31Hw8cgPt1BbyA',
    appId: '1:536108233592:ios:0789903383400f0a30ce8d',
    messagingSenderId: '536108233592',
    projectId: 'talk-easy-7b3a7',
    storageBucket: 'talk-easy-7b3a7.firebasestorage.app',
    iosBundleId: 'com.example.talkEasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2ilJGagVaZM5bYPxwt31Hw8cgPt1BbyA',
    appId: '1:536108233592:ios:0789903383400f0a30ce8d',
    messagingSenderId: '536108233592',
    projectId: 'talk-easy-7b3a7',
    storageBucket: 'talk-easy-7b3a7.firebasestorage.app',
    iosBundleId: 'com.example.talkEasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBthGXW1FU2bJ3L7yPMKw0jU7ns37Th2q8',
    appId: '1:536108233592:web:fe1e74690c7abf6730ce8d',
    messagingSenderId: '536108233592',
    projectId: 'talk-easy-7b3a7',
    authDomain: 'talk-easy-7b3a7.firebaseapp.com',
    storageBucket: 'talk-easy-7b3a7.firebasestorage.app',
    measurementId: 'G-DT8ECQYRX2',
  );

}